version: 2.1

orbs:
  architect: giantswarm/architect@6.15.0

workflows:
  build-tools:
    jobs:
    - architect/push-to-registries:
        context: architect
        name: push-to-registries-changelogger
        image: giantswarm/shield-changelogger
        dockerfile: ./tools/changelogger/Dockerfile
        build-context: ./tools/changelogger
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/push-to-registries:
        context: architect
        name: push-to-registries-values-sync
        image: giantswarm/shield-values-sync
        dockerfile: ./tools/values-sync/Dockerfile
        build-context: ./tools/values-sync
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/push-to-registries:
        context: architect
        name: push-to-registries-schema-gen
        image: giantswarm/shield-schema-gen
        dockerfile: ./tools/schema-gen/Dockerfile
        build-context: ./tools/schema-gen
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
