version: 2.1

orbs:
  architect: giantswarm/architect@6.14.1

workflows:
  build-tools:
    jobs:
    - architect/go-build:
        name: go-build-changelogger
        binary: changelogger
        path: ./tools/changelogger
        resource_class: large
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries-changelogger
        dockerfile: ./tools/changelogger/Dockerfile
        requires:
        - go-build-changelogger
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/go-build:
        name: go-build-values-sync
        binary: values-sync
        path: ./tools/values-sync
        resource_class: large
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries-values-sync
        dockerfile: ./tools/values-sync/Dockerfile
        requires:
        - go-build-values-sync
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master

    - architect/go-build:
        name: go-build-schema-gen
        binary: schema-gen
        path: ./tools/schema-gen
        resource_class: large
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries-schema-gen
        dockerfile: ./tools/schema-gen/Dockerfile
        requires:
        - go-build-schema-gen
        filters:
          tags:
            only: /^v.*/
          branches:
            ignore:
            - main
            - master
